version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  iam-service:
    lang: node10-express
    handler: ./iam-service
    image: iam-service:latest
    environment_file:
      - ./iam-service/env.yml
