# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-

      - run:
          name: Install dependencies if no cache is available
          command: |
            if [ ! -d "node_modules" ]; then
              echo "node_modules not available"
              yarn install --frozen-lockfile
            else
              echo "node_modules cache available"
            fi

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # build
      - run: yarn run build

      - persist_to_workspace:
          root: ./
          paths:
            - dist

  deploy:
    executor: node-executor

    steps:
      # - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: npx wrangler publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
